### PR TITLE
reworked & added interface IP for win & lin

### PR DESCRIPTION
**Pull request by AtakanColak**
Hiya, I came across this library when I was looking for a way to get the default IP address of a computer. Wanted to add that functionality over it so anyone in the same need could use it. Tested DefaultInterface() on 4 different Windows and 11 different Linux VMs. Please review, thank you.

### CODE REVIEW

**Comment by AtakanColak** [comment]
@jackpal please review

**Comment by jackpal** [comment]
Thanks very much for the pull request. I will try to review it soon. (The delay is because I am between PCs. I gave my old PC to one of my kids for COVID schooling, and my replacement laptop hasn't arrived yet. It should arrive in the next week or so.)

**Comment by AtakanColak** [comment]
No worries, feel free to ask any for any questions or request changes.

**Comment by jackpal** [comment]
I made two post-commit changes:

1) I added a \n to the end of the .gitignore file.

2) I commented out the Linux interfaceTestCases, since they failed when run on my Darwin machine.

If you can figure out how to make them pass in general, I'd be happy to take a pull request that restores them.

**Comment by AtakanColak** [comment]
Thank you, I couldn't really figure out how to do that in general that is why I added a comment.

**Pull request merged**
